### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by Nacharuvsko** [Chopper1337/Http.cat-Discord-Bot#1]
![Az9cD6mFZkblE5RLH-0u3Ab22VbP2VwPuD6QObGt5fyBiG--5klrhcWob0zVO5GyvvichxekIhpvfs76UxwQ7D6O](https://user-images.githubusercontent.com/66919449/208424754-1088a727-0407-46f5-96dc-2dcb0935b3d7.jpg)
Fix pls

**Comment by Chopper1337** [comment]
![IMG_20221219_122351](https://user-images.githubusercontent.com/43015696/208425543-08545f22-dd6e-4d5b-a841-6bc96d15c145.jpg)
Familiar? @Nacharuvsko

**Comment by Nacharuvsko** [comment]
You write unsafe code. Reported absiuvufe communications and blcoksed retadr
